# Generated by Django 3.1.8 on 2022-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220523_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
